import type { MobileShortcutDirection } from "../components/MobileShortcutFab";
import type { WorkspaceMode } from "../appState";
import type { AppLocale } from "../i18n";
import type { KeyboardShortcutBindings } from "../keyboardShortcuts";
import type { TerminalNotification } from "../terminalNotifications";
import type { AppPreferences } from "../userPreferences";
import type { useAgentRecordData } from "./useAgentRecordData";
import type { useAppCommandActions } from "./useAppCommandActions";
import type { useAppUiState } from "./useAppUiState";
import type { useAuthenticatedAppQueries } from "./useAuthenticatedAppQueries";
import type { useAuxTerminalWindow } from "./useAuxTerminalWindow";
import type { useClientLifecycleActions } from "./useClientLifecycleActions";
import type { useCustomQuickKeys } from "./useCustomQuickKeys";
import type { useOnboardingActions } from "./useOnboardingActions";
import type { useTerminalArtifactDrawer } from "./useTerminalArtifactDrawer";
import type { useTerminalCreateActions } from "./useTerminalCreateActions";
import type { useTerminalCreationMutations } from "./useTerminalCreationMutations";
import type { useTerminalDeleteActions } from "./useTerminalDeleteActions";
import type { useTerminalDeletionMutations } from "./useTerminalDeletionMutations";
import type { useTerminalNotificationActions } from "./useTerminalNotificationActions";
import type { useTerminalSelectionActions } from "./useTerminalSelectionActions";

export type UseAppPresentationControllerArgs = {
  appLocale: AppLocale;
  authEnabled: boolean;
  agentRecordModal: ReturnType<typeof useAgentRecordData>;
  auxTerminalStarting: boolean;
  auxTerminalUnavailable: boolean;
  auxTerminalWindow: ReturnType<typeof useAuxTerminalWindow>;
  commandActions: ReturnType<typeof useAppCommandActions>;
  creation: ReturnType<typeof useTerminalCreationMutations>;
  customQuickKeysState: ReturnType<typeof useCustomQuickKeys>;
  deletion: ReturnType<typeof useTerminalDeletionMutations>;
  deleteActions: ReturnType<typeof useTerminalDeleteActions>;
  drawer: ReturnType<typeof useTerminalArtifactDrawer>;
  focusSelectedTerminal: () => void;
  handleKeyboardShortcutBindingsChange: (bindings: KeyboardShortcutBindings) => void;
  isMobileLayout: boolean;
  lifecycle: ReturnType<typeof useClientLifecycleActions>;
  notifications: TerminalNotification[];
  notificationActions: ReturnType<typeof useTerminalNotificationActions>;
  onboardingActions: ReturnType<typeof useOnboardingActions>;
  onLogout: () => void;
  onAppLocaleChange: (locale: AppLocale) => void;
  onAppPreferencesSave: (preferences: AppPreferences) => Promise<AppPreferences>;
  onFocusProjectTodo: (projectPath: string, todoId: string) => void;
  onOpenProjectTodoBoard: () => void;
  onSelectWorkspaceMode: (mode: WorkspaceMode) => void;
  queries: ReturnType<typeof useAuthenticatedAppQueries>;
  selection: ReturnType<typeof useTerminalSelectionActions>;
  submitAgentPreviewQuickInput: (draft: string) => boolean;
  submitMobileShortcutDirection: (direction: MobileShortcutDirection) => boolean;
  terminalCreateActions: ReturnType<typeof useTerminalCreateActions>;
  toggleTerminalSwitcherMode: () => void;
  toggleVirtualKeysVisibility: () => void;
  toggleWorkspaceMode: () => void;
  ui: ReturnType<typeof useAppUiState>;
  virtualKeysVisible: boolean;
  closeClientSwitcher: () => void;
  closeTerminalSwitcher: () => void;
};
