from __future__ import annotations

from importlib import import_module

_EXPORT_MODULES = {
    "WindowTitle": "app.platform.common_schemas",
    "WindowText": "app.platform.common_schemas",
    "WindowTitleTag": "app.platform.common_schemas",
    "WindowStatusIn": "app.platform.common_schemas",
    "AgentKindIn": "app.platform.common_schemas",
    "AgentConfigSectionKindIn": "app.platform.common_schemas",
    "ClientName": "app.platform.common_schemas",
    "ClientStatusOut": "app.platform.common_schemas",
    "ClientRuntimeOut": "app.platform.common_schemas",
    "BootstrapHost": "app.platform.common_schemas",
    "BootstrapUsername": "app.platform.common_schemas",
    "BootstrapPrivateKey": "app.platform.common_schemas",
    "BootstrapServerUrl": "app.platform.common_schemas",
    "LoginSecret": "app.platform.common_schemas",
    "CaptchaId": "app.platform.common_schemas",
    "CaptchaAnswer": "app.platform.common_schemas",
    "RegistrationKey": "app.platform.common_schemas",
    "AgentConfigSelectionItemIn": "app.platform.common_schemas",
    "AgentConfigSelectionSectionIn": "app.platform.common_schemas",
    "AgentConfigSelectionIn": "app.platform.common_schemas",
    "AgentLaunchIn": "app.platform.common_schemas",
    "BootstrapClientIn": "app.schemas.clients",
    "BootstrapClientOut": "app.schemas.clients",
    "LoginIn": "app.platform.auth_schemas",
    "LoginOut": "app.platform.auth_schemas",
    "AuthStatusOut": "app.platform.auth_schemas",
    "CaptchaOut": "app.platform.auth_schemas",
    "KeycloakPublicConfigOut": "app.platform.auth_schemas",
    "ClientRegistrationKeyCreateIn": "app.schemas.clients",
    "ClientRegistrationKeyOut": "app.schemas.clients",
    "DirectClientRegisterIn": "app.schemas.clients",
    "DirectClientRegisterOut": "app.schemas.clients",
    "ClientUpdateOut": "app.schemas.clients",
    "ClientOut": "app.schemas.clients",
    "ClientPatchIn": "app.schemas.clients",
    "ClientUpdateCompleteIn": "app.schemas.clients",
    "WorkStatusOut": "app.schemas.windows",
    "TreeWindowOut": "app.schemas.windows",
    "GitWorktreeActivityOut": "app.schemas.windows",
    "WindowActivityOut": "app.schemas.windows",
    "GitWorktreeRunOut": "app.schemas.windows",
    "GitWorktreeRunListOut": "app.schemas.windows",
    "ClientWindowsActivityOut": "app.schemas.windows",
    "TerminalProjectOut": "app.schemas.windows",
    "ProjectBrowseRootOut": "app.schemas.windows",
    "ProjectBrowseRootListOut": "app.schemas.windows",
    "ProjectOut": "app.schemas.windows",
    "ProjectFileEntryOut": "app.schemas.windows",
    "ProjectFileListOut": "app.schemas.windows",
    "ProjectFileContentOut": "app.schemas.windows",
    "ProjectFileSaveIn": "app.schemas.windows",
    "ProjectFileUploadIn": "app.schemas.windows",
    "ProjectFileUploadOut": "app.schemas.windows",
    "TerminalNotificationOut": "app.schemas.windows",
    "TerminalNotificationListOut": "app.schemas.windows",
    "TerminalNotificationAckIn": "app.schemas.windows",
    "ManualWorkStatusIn": "app.schemas.windows",
    "TreeFolderOut": "app.schemas.windows",
    "FolderCreateIn": "app.schemas.windows",
    "FolderOut": "app.schemas.windows",
    "WindowCreateIn": "app.schemas.windows",
    "WindowCloneIn": "app.schemas.windows",
    "ProjectTodoCreateIn": "app.schemas.project_todos",
    "ProjectTodoDispatchIn": "app.schemas.project_todos",
    "ProjectTodoListItemOut": "app.schemas.project_todos",
    "ProjectTodoListOut": "app.schemas.project_todos",
    "ProjectTodoOut": "app.schemas.project_todos",
    "ProjectTodoPatchIn": "app.schemas.project_todos",
    "ProjectTodoReferenceOut": "app.schemas.project_todos",
    "ProjectTodoRelationOut": "app.schemas.project_todos",
    "ArtifactKind": "app.schemas.artifacts",
    "ArtifactTitle": "app.schemas.artifacts",
    "TerminalArtifactCreateIn": "app.schemas.artifacts",
    "TerminalArtifactOut": "app.schemas.artifacts",
    "TerminalArtifactListOut": "app.schemas.artifacts",
    "WindowPatchIn": "app.schemas.agent_records",
    "SummaryJobOut": "app.schemas.agent_records",
    "WindowOut": "app.schemas.agent_records",
    "AgentSessionOut": "app.schemas.agent_records",
    "AgentEventProjectionOut": "app.schemas.agent_records",
    "AgentEventOut": "app.schemas.agent_records",
    "AgentRecordOut": "app.schemas.agent_records",
    "AgentChatMessageOut": "app.schemas.agent_records",
    "AgentChatRecordOut": "app.schemas.agent_records",
    "AgentConfigItemOut": "app.schemas.agent_records",
    "AgentConfigSectionOut": "app.schemas.agent_records",
    "AgentConfigOut": "app.schemas.agent_records",
    "AgentConfigToggleIn": "app.schemas.agent_records",
    "AgentClientOut": "app.schemas.agent_records",
    "AgentClientListOut": "app.schemas.agent_records",
    "AgentProfileOut": "app.schemas.agent_records",
    "AgentProfileListOut": "app.schemas.agent_records",
    "AgentProfileCreateIn": "app.schemas.agent_records",
    "AgentProfileUpdateIn": "app.schemas.agent_records",
    "CommandHistoryItemOut": "app.schemas.agent_records",
    "CommandHistoryOut": "app.schemas.agent_records",
    "WindowTitleHistoryItemOut": "app.schemas.agent_records",
    "WindowTitleHistoryOut": "app.schemas.agent_records",
    "SummaryJobRetryIn": "app.schemas.windows",
    "IngestEventOut": "app.schemas.misc",
    "SearchResultOut": "app.platform.search_schemas",
    "SearchOut": "app.platform.search_schemas",
    "TerminalRecentOut": "app.schemas.misc",
    "GlobalTerminalRecentOut": "app.schemas.misc",
    "TerminalRecentPageOut": "app.schemas.misc",
    "GlobalTerminalRecentPageOut": "app.schemas.misc",
    "TerminalRecentTouchIn": "app.schemas.misc",
    "CustomQuickKeyOut": "app.platform.ui_settings_schemas",
    "CustomQuickKeysOut": "app.platform.ui_settings_schemas",
    "CustomQuickKeysPutIn": "app.platform.ui_settings_schemas",
    "ProjectSummaryOut": "app.schemas.misc",
    "ProjectSummarySummarizeIn": "app.schemas.misc",
}

__all__ = list(_EXPORT_MODULES)


def __getattr__(name: str):
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
